### PR TITLE
Add method ElasticsearchEngine.generate_mappings()

### PR DESCRIPTION
**Pull request by simonvadee**
This PR moves some code previously defined in [fhirpath_helpers](github.com/nazrulword/fhirpath_helpers) to fhirpath.
The goal is to make it easier to generate the elasticsearch mapping used to index FHIR data. It allows to specify `reference_analyzer`  and `token_normalizer` which are useful to provide advanced search features as described by the [FHIR search specification](http://hl7.org/fhir/search.html).

### CODE REVIEW

**Comment by nazrulworld** [comment]
@simonvadee Thank you so much, I see one mypy linting issue (minor), that's OK I can also fix it.

**Comment by simonvadee** [comment]
@nazrulworld I'll take care of it today!

**Comment by nazrulworld** [comment]
LGTM

**Comment by nazrulworld** [comment]
@simonvadee I have a question. You know that DateTime and Date type FHIR can hold only year or year+month.
So those value is saved as a string value instead datetime/date object. How could we handle in elasticsearch mapping, that situation?

**Comment by simonvadee** [comment]
FHIR doc says:
```
date 	A date, or partial date (e.g. just year or year + month) as used in human communication. The format is YYYY, YYYY-MM, or YYYY-MM-DD, e.g. 2018, 1973-06, or 1905-08-23.
dateTime 	A date, date-time or partial date (e.g. just year or year + month) as used in human communication. The format is YYYY, YYYY-MM, YYYY-MM-DD or YYYY-MM-DDThh:mm:ss+zz:zz, e.g. 2018, 1973-06, 1905-08-23, 2015-02-07T13:28:17-05:00 or 2017-01-01T00:00:00.000Z. If hours and minutes are specified, a time zone SHALL be populated.```
which translates to:
```
{
   "type": "date",
   "format": "date_time_no_millis||date_optional_time",
   "store": False,
}
```
in the ES mapping. More tests coming for searching on dates in a next PR!

**Pull request merged**
